project: 
  type: website

website:
  title: "Jorge Córdova - Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/jorgeecordova25/jorgeecordova25.github.io.git
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Jorge Córdova 2026©"
    right: 
      - icon: linkedin
        href: Your_LinkedIn_URL

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "Introduction"
        file: introduction.qmd
      - text: "Data Exploration"
        file: exploration.qmd
      - text: "JSON"
        file: json.qmd
      - text: "SQL"
        file: sql.qmd
      - text: "Machine Learning"
        file: ml.qmd
      - text: "Data Cleaning"
        file: cleansing.qmd
  
  # learn more about navication here https://quarto.org/docs/websites/website-navigation.html
  # comment out any of the sections below to turn off the sidebar

  sidebar: 
    - title: "Introduction"
      style: "docked"
      background: light
      contents:
        - text: "Introduction"
          file: introduction.qmd
        - text: "---"
        - text: "Project 0"
          file: Introduction_project/project0.qmd
        - text: "---"
    - title: "Data Exploration"
      style: "docked"
      background: light
      contents:
        - text: "Data Exploration"
          file: exploration.qmd
        - text: "---"
        - text: "What’s in a Name?"
          file: Exploration_Projects/project1.qmd
        - text: "---"
    - title: "JSON"
      style: "docked"
      background: light
      contents:
        - text: "JSON"
          file: json.qmd
        - text: "---"
        - text: "Late Flights & Missing Data (JSON)"
          file: json/project1.qmd
        - text: "---"
    - title: "SQL"
      style: "docked"
      background: light
      contents:
        - text: "SQL"
          file: sql.qmd
        - text: "---"
        - text: "Finding Relationships in Baseball"
          file: sql/project1.qmd
        - text: "---"
    - title: "Machine Learning"
      style: "docked"
      background: light
      contents:
        - text: "Machine Learning"
          file: ml.qmd
        - text: "---"
        - text: "Can You Predict That?"
          file: Machine_Learning/project1.qmd
        - text: "---"
    - title: "Cleaning Data"
      style: "docked"
      background: light
      contents:
        - text: "Cleaning Data"
          file: cleansing.qmd
        - text: "---"
        - text: "The War with Star Wars"
          file: Cleaning_Data_Project/project1.qmd
        - text: "---"
  
format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



